# Generated by Django 4.2.7 on 2023-12-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_paymenttable_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttable',
            name='user_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
