# Generated by Django 4.2.7 on 2023-12-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_paymenttable_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttable',
            name='user_id',
        ),
        migrations.AddField(
            model_name='paymenttable',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='paymenttable',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
